spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/devopshub
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
